// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteDB;

#nullable disable

namespace SQLiteDB.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250714145317_RemoveTableCountry")]
    partial class RemoveTableCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SQLiteDB.Country", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("SQLiteDB.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountryCId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryCId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SQLiteDB.User", b =>
                {
                    b.HasOne("SQLiteDB.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
